CREATE TABLE "writeup-app_writeup_author" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "writeup-app_writeup_author_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"author" text
);
--> statement-breakpoint
CREATE TABLE "writeup-app_writeup_authors_writeups" (
	"author_id" integer,
	"writeup_id" integer
);
--> statement-breakpoint
CREATE TABLE "writeup-app_writeup_bug" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "writeup-app_writeup_bug_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"bug" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "writeup-app_writeup_bugs_writeups" (
	"bug_id" integer,
	"writeup_id" integer
);
--> statement-breakpoint
CREATE TABLE "writeup-app_writeup_program" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "writeup-app_writeup_program_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"program" text
);
--> statement-breakpoint
CREATE TABLE "writeup-app_writeup_programs_writeups" (
	"program_id" integer,
	"writeup_id" integer
);
--> statement-breakpoint
CREATE TABLE "writeup-app_writeup" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "writeup-app_writeup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text,
	"link" text,
	"published_at" timestamp,
	"added_at" timestamp,
	"bounty" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"notes" text,
	"read_at" timestamp,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"username" text,
	"display_username" text,
	CONSTRAINT "user_email_unique" UNIQUE("email"),
	CONSTRAINT "user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_authors_writeups" ADD CONSTRAINT "writeup-app_writeup_authors_writeups_author_id_writeup-app_writeup_author_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."writeup-app_writeup_author"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_authors_writeups" ADD CONSTRAINT "writeup-app_writeup_authors_writeups_writeup_id_writeup-app_writeup_id_fk" FOREIGN KEY ("writeup_id") REFERENCES "public"."writeup-app_writeup"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_bugs_writeups" ADD CONSTRAINT "writeup-app_writeup_bugs_writeups_bug_id_writeup-app_writeup_bug_id_fk" FOREIGN KEY ("bug_id") REFERENCES "public"."writeup-app_writeup_bug"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_bugs_writeups" ADD CONSTRAINT "writeup-app_writeup_bugs_writeups_writeup_id_writeup-app_writeup_id_fk" FOREIGN KEY ("writeup_id") REFERENCES "public"."writeup-app_writeup"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_programs_writeups" ADD CONSTRAINT "writeup-app_writeup_programs_writeups_program_id_writeup-app_writeup_program_id_fk" FOREIGN KEY ("program_id") REFERENCES "public"."writeup-app_writeup_program"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_programs_writeups" ADD CONSTRAINT "writeup-app_writeup_programs_writeups_writeup_id_writeup-app_writeup_id_fk" FOREIGN KEY ("writeup_id") REFERENCES "public"."writeup-app_writeup"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;