CREATE TABLE "writeup-app_writeup_note" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "writeup-app_writeup_note_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"note" text,
	"writeup_id" integer,
	"user_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "writeup-app_writeup_read" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "writeup-app_writeup_read_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"writeup_id" integer,
	"user_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_note" ADD CONSTRAINT "writeup-app_writeup_note_writeup_id_writeup-app_writeup_id_fk" FOREIGN KEY ("writeup_id") REFERENCES "public"."writeup-app_writeup"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_note" ADD CONSTRAINT "writeup-app_writeup_note_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_read" ADD CONSTRAINT "writeup-app_writeup_read_writeup_id_writeup-app_writeup_id_fk" FOREIGN KEY ("writeup_id") REFERENCES "public"."writeup-app_writeup"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup_read" ADD CONSTRAINT "writeup-app_writeup_read_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "writeup-app_writeup" DROP COLUMN "notes";--> statement-breakpoint
ALTER TABLE "writeup-app_writeup" DROP COLUMN "read_at";